str1="hEllo_upes"
a=23
str2=" welcome to world of , coding {}"
print(str1)
print(str2)
print(len(str1))
print(str1 +str2)
print(str1.upper())
print(str1.lower())
print(str2.replace("coding","computer"))
print(str1[1])
print(str1[1:7])
print(str2[1:17:2])
print(str1[::2])
print("upes" in str1)
print("coding" not in str2)
print(str2.strip())
print(str2.split(','))
print(str2.format(a))
print(str1.index("up"))
print(str1.swapcase())
print(str2.count('o'))
print(str1.capitalize())
print(str2.title())
