name=input("Enter your name-->")
sap_id=int(input("Enter your sap ID-->"))
roll_no=input("Enter your roll number-->")
dep=input("Enter the department-->")
course=input("Enter your course-->")
univ_name=input("Enter the name of the university-->")
univ_pin=int(input("Enter the pin code of the university-->"))
print(3*"\n")
print('NAME-->',name,"\n",'SAP ID-->',sap_id,"\n",'ROLL NO.-->',roll_no)
print('DEPARTMENT-->',dep,"\n",'COURSE-->',course)
print('\nUNIVERSITY DETAILS\nNAME-->',univ_name,"\n",'PIN CODE-->',univ_pin)
